# Generated by Django 2.1.2 on 2019-12-11 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20191210_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='F_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='施設名')),
                ('I_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='入力者氏名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('quontity', models.IntegerField(blank=True, null=True, verbose_name='何kgくらいでそうか')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='いつだせるか')),
                ('vegetable', models.IntegerField(blank=True, choices=[(1, '人参'), (2, '大根'), (3, 'じゃがいも'), (4, 'キャベツ'), (5, 'ホウレンソウ'), (6, 'ピーマン'), (7, 'なんでもいい')], null=True, verbose_name='出せる野菜')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='作成時間')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'サンプル',
                'verbose_name_plural': 'サンプル',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='いつほしいか'),
        ),
    ]
