# Generated by Django 2.1.2 on 2020-01-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191216_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='メールアドレス'),
        ),
    ]
