# Generated by Django 2.1.2 on 2020-01-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_item_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='good',
            field=models.IntegerField(null=True, verbose_name='いいね'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quontity',
            field=models.IntegerField(blank=True, null=True, verbose_name='何kg出せるか'),
        ),
    ]
